server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://47.102.104.144:3306/zhongchuan?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 2023Aii1008
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.shu.backend: INFO
#  file:
#    name: app.log
#    path: /var/logs